[uwsgi]
plugins-dir = /opt/homebrew/opt/uwsgi/libexec/uwsgi
plugins = python3
module = app:app
http-socket = 0.0.0.0:8080
master = true
processes = 2
lazy-apps = true
enable-threads = true
virtualenv = .venv
die-on-term = true
