apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  labels:
    app: flask-instrumentation-test
data:
  OTEL_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_SERVICE_NAME: "flask_instrumentation_test"
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://staging.ctrlb.dev/engine/api/default"
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "https://staging.ctrlb.dev/engine/api/default/flask_instrumentation_test/_otel/v1/logs"
  PORT: "8080"
